name: "hash"

_target_: "networks.hash_networks.HashNet"
# Recursively instantiate object `hash_embedding` as an argument to HashNet's constructor
_recursive_: true

in_features: 2
out_features: 3
hidden_features: 64
hidden_layers: 2
outermost_linear: true

hash_embedding:
  _target_: "networks.hash_networks.HashEmbedding"
  coord_dim: 2
  n_levels: 16
  n_features_per_entry: 2
  log2_hashtable_size: 14
  base_resolution: 16
  finest_resolution: 512
