name: "nerf"

_target_: "networks.nerf_networks.NeRFNetwork"
_recursive_: true

grid_min: -1
grid_max: 1
density_scale: 1
min_near: 0.2
num_steps_per_ray: 512

density_net:
  _target_: "networks.hash_networks.HashNet"
  in_features: 3
  hidden_features: 64
  hidden_layers: 1
  out_features: 16
  outermost_linear: true
  hash_embedding:
    _target_: "networks.hash_networks.HashEmbeddingUnravel"
    coord_dim: 3
    grid_min: -1
    grid_max: 1
    n_levels: 16
    n_features_per_entry: 2
    log2_hashtable_size: 14
    base_resolution: 16
    finest_resolution: 512

direction_encoder:
  _target_: "networks.misc_networks.SHEncoder"
  input_features: 3
  degree: 4

color_hidden_features: 64
color_hidden_layers: 2
color_out_features: 3
color_out_activation:
  _target_: "torch.nn.Sigmoid"
