defaults:
  - simple_trainer_for_hash

_target_: "trainers.hash_freeze_trainer.HashFreezeTrainer"
_recursive_: false

load_ckpt_path: null
freeze_hash: false
freeze_mlp: true
freeze_at: end_of_region0
