defaults:
  - simple_trainer_for_hash_giga

_target_: "trainers.hash_freeze_trainer.HashFreezeTrainerGiga"
_recursive_: false

load_ckpt_path: null
freeze_hash: false
freeze_mlp: true
freeze_at: init
