defaults:
  - simple_trainer_for_hash

_target_: "trainers.hash_freeze_trainer.HashFreezeTrainer"
_recursive_: false

load_ckpt_path: null
freeze_hash: false
freeze_mlp: true
freeze_at: init

total_steps: 1e5
switch_region_every_steps: 10

summary_every_steps: 1000
eval_every_steps: 1000
checkpoint_every_steps: 1000
