defaults:
  - simple_trainer

_target_: "trainers.node_sharpen_trainer.NodeSharpenTrainer"
_recursive_: false

sharpen_optimizer:
  _target_: torch.optim.Adam
  lr: 2e-5
  weight_decay: 0

sharpen_ratio: log
which_layers_to_sharpen: [0]
sharpen_every_steps: 50
sharpen_on_grid: current
