_target_: "trainers.simple_trainer.SimpleTrainer"
_recursive_: false

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

total_steps: 1000
cuda_if_available: True
switch_region_every_steps: 100

summary_every_steps: 20
eval_every_steps: 20
