_target_: "trainers.simple_trainer.SimpleTrainer"
_recursive_: false

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0

continual: True
l1_lambda: 0

total_steps: 1000
gpu_if_available: True
switch_region_every_steps: 250

summary_every_steps: 20
eval_every_steps: 20
checkpoint_every_steps: 250
