defaults:
  - simple_trainer

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-2
  betas: [0.9, 0.99]
  eps: 1e-15
  weight_decay: 0

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

gpu_if_available: False
